### ISSUE TITLE
Update to use new assets abstraction rather than hard coded paths

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-registry#30]
E.g. see constants in \_config.php, RegistryImportFeed 

This module saves imported CSV files via model admins into `assets/_imports/ClassName/import-xyz123.csv`, which is then used for "version feeds" via RegistryImportFeedController as part of an RSS feed for the frontend users.

We would ideally convert the filesystem calls into something that uses the SS4 file abstraction system, rather than writing directly to the "assets" folder, which may not always exist on the filesystem (via the flysystem adapter).

cc @tractorcow

**Comment by robbieaverill** [comment]
One option is to replace the way this works with a SilverStripe File model.

It's a little confusing, since the relationship would be relatively dynamic in that a RegistryPage which uses FooModel as its data source could have a method like "getImportFeeds" which looks up any RegistryFeed record (has_one File) that is associated to the data class that the page is representing.

In that way it might look something like this:

```
RegistryPage represents FooModel

ImportFeed:
  a: has_one File -> 2-jan-2017.csv, dataclass FooModel
  b: has_one File -> 3-jan-2017.csv, dataclass FooModel
  c: has_one File -> 4-jan-2017.csv, dataclass BazModel
  d: has_one File -> 5-jan-2017.csv, dataclass BarModel
```

Then maybe `RegistryPageController::getImportFeeds` could return something like:

```php
return ImportFeed::get()->filter(['DataClass' => get_class($this->dataRecord)]);
```

... and templates could be adjusted to accept a list of `ImportFeed` models rather than filenames, knowing each ImportFeed has_one File.

What do you think @tractorcow ?
